### PR TITLE
Flickr with OAuth 1.0a addendum

### PR DESCRIPTION
**Pull request by cdn**
PHP OAuth class use under PHP7.0 requires the callback parameter unlike PHP5.

### CODE REVIEW

**Comment by mapkyca** [comment]
Hmm... I still appear to be getting the same error. It's possible I'm doing something wrong, I'll investigate a bit more when I'm not monumentally tired!

**Comment by cdn** [comment]
The 411 (for php7.0) [or a 401 (for php5)] is now for the method call on line 50.

http://php.net/manual/en/oauth.getaccesstoken.php doesn’t have a helpful suggestion.

It’s possible this is something I ran into when I initially created the pull request; there might be a backend preference for HTTP over HTTPS with some of Flickr’s URLs. (iirc it was only the first one)

When it appeared to work, it may have been a case of prior authorisation hanging around; I get those HTTP responses having Revoked my app on Flickr’s user page(s).

**Comment by mapkyca** [comment]
Hmm... I tried changing the URL to http, and got the same result....

**Comment by cdn** [comment]
I ended up using two OAuth implementations because I couldn’t wrangle the external library to do the part the PHP class used to successfully accomplish.

**Pull request merged**
