### PR TITLE
Revised Flickr add–on for Known using OAuth 1.0a

### LINKED ISSUE #4: Flickr connection fails
After setting up the flickr plugin on the self hosted version of Known I can not connect to my account.  The flickr service complains about a lack of callback URL

Steps to repeat:
1. enable flickr plugin
2. go to administration flickr
3. enter in api key and app secret as per instructions.  Callback url specified by plugin is set to http://rawlinson.us/flickr/callback
4. go to settings -> flickr
5. click on "click here to connect Flickr to your account"
6. flickr loads with message: "Oops! Flickr can't find a valid callback URL."

### PR DESCRIPTION
**Pull request by cdn**
Replaces external library, so not quite an answer to #13 

Will probably need more revision before merge

Likely fixes #4 #11

### CODE REVIEW

**Comment by cdn** [comment]
I don’t known whether SmugMug’s take over of Flickr will have any API implications.

**Comment by mapkyca** [comment]
Hmm... I've merged and tried this, but I'm getting

"Invalid auth/bad request (got a 411, expected HTTP/1.1 20X or a redirect)" 

..on connect.

Any thoughts?

**Comment by mapkyca** [comment]
Had to revert, but please feel free to re-submit

**Comment by cdn** [comment]
411 occurs back on version 0.9.9 2018032701 backed by PostgreSQL

It didn’t occur on version 0.9.9 2017051501 backed by SQLite.

Today, having disconnected the SQLite blog: gets through to Flickr (https://www.flickr.com/services/oauth/authorize?oauth_token=[hexadecimal–hyphenated string]&perms=write) (when oauth module is actually installed).

I don’t know why there’s an HTTP 411 Length error [yet].

**Comment by cdn** [comment]
Addendum: SQLite–backed blog is on php5 FPM
PostgreSQL–backed blog is on php7.0 FPM

Line 35 is the call to the php oauth library’s getRequestToken method, perhaps that has changed between PHP versions?

**Comment by mapkyca** [comment]
If it helps this was PHP 7 with a mongo back end.

**Comment by cdn** [comment]
PostgreSQL with PHP5 still works.

PostgreSQL with PHP7.0 works if I add $callback as the second parameter, per the 8–year old note: http://php.net/manual/en/oauth.getrequesttoken.php

**Comment by mapkyca** [comment]
Cool! Could you update and resubmit the PR?

**Pull request merged**
